---
- name: add repository GPG key for Docker
  become: true
  ansible.builtin.get_url:
    url: https://download.docker.com/linux/{{ ansible_distribution | lower }}/gpg
    dest: /etc/apt/trusted.gpg.d/docker.asc

- name: add docker repository
  become: true
  ansible.builtin.deb822_repository:
    name: vscode
    types: deb
    uris: https://download.docker.com/linux/{{ ansible_distribution | lower }}
    suites: { { ansible_distribution_release } }
    components: stable
    architectures: amd64
    signed_by: /etc/apt/trusted.gpg.d/docker.asc

- name: install docker packages
  become: true
  ansible.builtin.apt:
    name:
      - docker-ce
      - docker-ce-cli
