---

- name: check helm releases
  uri:
    url: https://api.github.com/repos/helm/helm/releases/latest
    return_content: yes
  register: releases
  tags:
    - system

- name: install or upgrade helm {{ releases.json.tag_name[1:] }}
  become: yes
  apt:
    deb: "{{ releases.json |to_json|from_json| json_query('assets[?contains(name, `minikube`) && contains(name, `.deb`)].browser_download_url | [0]') }}"
    state: present
  when: ansible_facts.packages['minikube'] is not defined or ansible_facts.packages['minikube'][0].version != releases.json.tag_name[1:]
  tags:
    - system
    - minikube
