---
- name: check ttl releases
  uri:
    url: https://api.github.com/repos/lance0/ttl/releases/latest
    return_content: true
  register: releases

- name: check ttl locally
  become: true
  become_user: "{{ username }}"
  stat:
    path: /usr/local/bin/ttl
  register: ttl_stat

- name: check ttl local version
  become: true
  become_user: "{{ username }}"
  command: /usr/local/bin/ttl --version
  register: ttl_version
  changed_when: false
  when: ttl_stat.stat.exists

- name: create temporary directory for archive
  ansible.builtin.tempfile:
    state: directory
    suffix: ttl
  register: ttl_temp
  when:
    - not ansible_check_mode
    - not ttl_stat.stat.exists or releases.json.tag_name[1:] not in ttl_version.stdout
  diff: false

- name: download ttl {{ releases.json.tag_name }}
  ansible.builtin.unarchive:
    dest: "{{ ttl_temp.path }}"
    src: "{{ releases.json |to_json|from_json| json_query('assets[?contains(name, `linux`) && contains(name, `x86_64`)].browser_download_url | [0]') }}"
    remote_src: true
  register: release_download
  diff: false
  when:
    - ttl_temp.path is defined

- name: install or upgrade ttl {{ releases.json.tag_name }}
  become: true
  copy:
    src: "{{ ttl_temp.path }}/ttl"
    dest: "/usr/local/bin/ttl"
    remote_src: true
    mode: 0755
  when:
    - ttl_temp.path is defined

- name: ttl shell completion
  become: true
  become_user: "{{ username }}"
  ansible.builtin.shell: "/usr/local/bin/ttl --completions fish > {{ config.fish }}/completions/ttl.fish"
  when:
    - ansible_facts.packages["fish"] is defined
    - ttl_temp.path is defined
