---

- name: check yq releases
  uri:
    url: https://api.github.com/repos/mikefarah/yq/releases/latest
    return_content: true
  register: releases
  tags: system

- name: check yq locally
  become: true
  become_user: "{{ username }}"
  stat:
    path: /usr/local/bin/yq
  register: yq_stat

- name: check yq local version
  become: true
  become_user: "{{ username }}"
  command: /usr/local/bin/yq --version
  register: yq_version
  changed_when: false
  when: yq_stat.stat.exists

- name: install or upgrade yq {{ releases.json.name }}
  become: true
  get_url:
    url: "{{ releases.json |to_json|from_json| json_query('assets[?contains(name, `linux`) && ends_with(name, `amd64`)].browser_download_url | [0]') }}"
    dest: "/usr/local/bin/yq"
    mode: 0755
  when:
    - not ansible_check_mode
    - not yq_stat.stat.exists or releases.json.tag_name not in yq_version.stdout
  tags: system
